/* The translation unit the captured build's `server` target starts from. Its
   configuration header is generated by the build, so capture must record a
   file that does not exist in the checked-in project. */
#include "config.h"

void worker(void);

static void prepare(void) {}

int main(void) {
    prepare();
#if CAPTURE_FEATURE
    worker();
#endif
    return 0;
}
